openapi: "3.0.0"
info:
  title: "33routes API Documentation"
  description: "API for Auth, User, Route, Collection, Comment, Search, File Storage, Moderation, Bug and Report Services."
  version: "1.0.0"
servers:
  - url: http://localhost:8100
  - url: https://33routes.ru
paths:


  /api/route/routes:
    get:
      summary: "Получение списка маршрутов"
      description: "Возвращает список id всех доступных маршрутов."
      parameters:
        - in: query
          name: pagination-page-number
          required: false
          schema:
            type: integer
            minimum: 1
          description: "Номер страницы для отображения (по умолчанию 1)"
          example: 1
        - in: query
          name: pagination-per-page
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 100
          description: "Количество элементов на странице (по умолчанию 10)"
          example: 10
      responses:
        200:
          description: "Список id маршрутов"
          headers:
            pagination-current-page:
              description: "Текущая страница пагинации"
              schema:
                type: integer
                example: 1
            pagination-total-elements:
              description: "Общее количество страниц"
              schema:
                type: integer
                example: 5
            pagination-per-page:
              description: "Количество элементов на странице"
              schema:
                type: integer
                example: 3
            pagination-total-pages:
              description: "Количество страниц"
              schema:
                type: integer
                example: 1
          content:
            application/json:
              schema:
                type: object
                properties:
                  routes:
                    type: array
                    items:
                      type: integer
                    description: "ID маршрута"
                example:
                  routes: [ 
                    1,
                    2,
                    3
                  ]

  /api/route/route/{route-id}:
    get:
      summary: "Просмотр информации о маршруте"
      description: "Возвращает подробную информацию о выбранном маршруте."
      parameters:
        - name: route-id
          in: path
          required: true
          schema:
            type: integer
            example: 123
      responses:
        200:
          description: "Детали маршрута"
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    type: object
                    properties:
                      user_id:
                        type: integer
                        description: "ID юзера"
                        example: 1
                      name:
                        type: string
                        description: "ID юзера"
                        example: "Алла Иванова"
                      image_url:
                        type: string
                        description: "url аватарки"
                        example: "url"
                  route:
                    type: object
                    properties:
                      route_id:
                        type: integer
                        description: "ID маршрута"
                        example: 123
                      name:
                        type: string
                        description: "Название маршрута"
                        example: "Mountain Trail"
                      url:
                        type: string
                        description: "URL маршрута"
                        example: "url"
                      description:
                        type: string
                        description: "Описание маршрута"
                        example: "A beautiful trail in the mountains"
                      length:
                        type: integer
                        description: "Длина маршрута в метрах"
                        example: 5000
                      duration:
                        type: integer
                        description: "Продолжительность маршрута в секундах"
                        example: 7200
                      tags:
                        type: array
                        items:
                          type: string
                          enum: ["forest", "park", "near_water"]
                        description: "Теги маршрута"
                        example: ["forest", "near_water"]
                      category:
                        type: string
                        enum: ["walking"]
                        description: "Категория маршрута"
                        example: "walking"
                      created_at:
                        type: integer
                        description: "Дата создания маршрута в формате Unix"
                        example: 1616179200
                      status:
                        type: string
                        enum: ["pending", "approved", "rejected"]
                        description: "Статус маршрута"
                        example: "approved"
                      is_deleted:
                        type: boolean
                        description: "Флаг удаления маршрута"
                        example: false
                      rating:
                        type: number
                        format: float
                        description: "Средний рейтинг маршрута"
                        example: 3.5
                      images:
                        type: array
                        items:
                          type: string
                        description: "Ссылки на изображения маршрута"
                        example: ["url_to_image1", "url_to_image2"]
                  points:
                    type: array
                    description: "Точки маршрута с координатами и дополнительной информацией"
                    items:
                      type: object
                      properties:
                        point_id:
                          type: integer
                          description: "ID точки маршрута"
                          example: 1
                        coordinate:
                          type: object
                          properties:
                            latitude:
                              type: number
                              format: float
                              description: "Широта"
                              example: 45.12345
                            longitude:
                              type: number
                              format: float
                              description: "Долгота"
                              example: 12.12345
                        time_offset:
                          type: integer
                          description: "Время в секундах с начала маршрута"
                          example: 300
                        elevation:
                          type: integer
                          description: "Высота точки над уровнем моря в метрах"
                          example: 200
                        speed:
                          type: number
                          format: float
                          description: "Скорость на этой точке маршрута"
                          example: 2.5
                        point_description:
                          type: string
                          description: "Описание точки маршрута"
                          example: "Поворот у дерева"
                        images:
                          type: array
                          items:
                            type: string
                          description: "Изображения, связанные с точкой маршрута"
                          example: ["url_to_image1", "url_to_image2"]
                example:
                  user:
                    user_id: 1
                    name: "Алла Майонезова"
                    image_url: "image"
                  route:
                    route_id: 123
                    name: "Mountain Trail"
                    url: "url"
                    description: "A beautiful trail in the mountains"
                    length: 5000
                    duration: 7200
                    tags: ["forest", "near_water"]
                    category: "walking"
                    created_at: 1616179200
                    rating: 3.5
                    images: ["url_to_image1", "url_to_image2"]
                  points:
                    - point_id: 1
                      coordinate:
                        latitude: 45.12345
                        longitude: 12.12345
                      time_offset: 300
                      elevation: 200
                      speed: 2.5
                      point_description: "Поворот у дерева"
                      images: ["url_to_image1", "url_to_image2"]

  /api/review/route/{route-id}/reviews:
    get:
      summary: "Получение списка рецензий маршрута"
      description: "Возвращает список рецензий, связанных с указанным маршрутом."
      parameters:
        - in: path
          name: route-id
          required: true
          schema:
            type: integer
          description: "ID маршрута"
        - in: query
          name: pagination-page-number
          required: false
          schema:
            type: integer
            minimum: 1
          description: "Номер страницы для отображения (по умолчанию 1)"
          example: 1
        - in: query
          name: pagination-per-page
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 100
          description: "Количество элементов на странице (по умолчанию 10)"
          example: 10
      responses:
        200:
          description: "Список рецензий маршрута"
          headers:
            pagination-current-page:
              description: "Текущая страница пагинации"
              schema:
                type: integer
                example: 1
            pagination-total-elements:
              description: "Общее количество страниц"
              schema:
                type: integer
                example: 5
            pagination-per-page:
              description: "Количество элементов на странице"
              schema:
                type: integer
                example: 3
            pagination-total-pages:
              description: "Количество страниц"
              schema:
                type: integer
                example: 1
          content:
            application/json:
              schema:
                type: object
                properties:
                  reviews:
                    type: array
                    items:
                      type: object
                      properties:
                        review_id:
                          type: integer
                          description: "ID рецензии"
                        user_id:
                          type: integer
                          description: "ID пользователя, оставившего рецензию"
                        rating:
                          type: number
                          format: float
                          description: "Рейтинг, выставленный пользователем"
                        comment:
                          type: string
                          description: "Текст рецензии"
                        created_at:
                          type: integer
                          description: "Дата создания рецензии в формате Unix"
                        images:
                          type: array
                          items:
                            type: string
                          description: "Ссылки на изображения"
                example:
                  reviews:
                    - review_id: 1
                      user_id: 123
                      rating: 4.5
                      comment: "Отличный маршрут!"
                      created_at: 1616179200
                      images: ["url_to_image1", "url_to_image2"]

  /api/review/route/{route-id}/review:
    post:
      summary: "Добавление рецензии"
      description: "Позволяет пользователю добавить рецензию к указанному маршруту."
      parameters:
        - in: path
          name: route-id
          required: true
          schema:
            type: integer
          description: "ID маршрута"
        - in: header
          name: session-token
          required: true
          schema:
            type: string
          description: "Токен сессии"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: integer
                  description: "ID пользователя"
                  example: 1
                rating:
                  type: number
                  format: float
                  description: "Рейтинг маршрута от 0 до 5"
                  example: 4.5
                comment:
                  type: string
                  description: "Текст рецензии"
                  example: "Amazing route, highly recommended!"
                images:
                  type: array
                  items:
                    type: string
                  description: "Ссылки на изображения рецензии"
                  example: ["url_to_image1", "url_to_image2"]
      responses:
        200:
          description: "Рецензия успешно добавлена"

    delete:
      summary: "Удаление рецензии"
      description: "Позволяет пользователю удалить свою рецензию для указанного маршрута."
      parameters:
        - in: path
          name: route-id
          required: true
          schema:
            type: integer
          description: "ID маршрута"
        - in: header
          name: session-token
          required: true
          schema:
            type: string
          description: "Токен сессии"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: integer
                  description: "ID пользователя"
                  example: 1
                review_id:
                  type: integer
                  description: "ID рецензии"
                  example: 1
      responses:
        200:
          description: "Рецензия успешно удалена"

  /api/comment/review/{review-id}/comments:
    get:
      summary: "Получить комментарии к маршруту"
      description: "Возвращает список комментариев, связанных с указанной рецензией."
      parameters:
        - in: path
          name: review-id
          required: true
          schema:
            type: string
          description: "ID рецензии"
      responses:
        200:
          description: "Список комментариев"
          headers:
            pagination-current-page:
              description: "Текущая страница пагинации"
              schema:
                type: integer
                example: 1
            pagination-total-elements:
              description: "Общее количество страниц"
              schema:
                type: integer
                example: 5
            pagination-per-page:
              description: "Количество элементов на странице"
              schema:
                type: integer
                example: 3
            pagination-total-pages:
              description: "Количество страниц"
              schema:
                type: integer
                example: 1
          content:
            application/json:
              schema:
                type: object
                properties:
                  comments:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          description: "ID комментария"
                        user_id:
                          type: integer
                          description: "ID пользователя, оставившего комментарий"
                        text:
                          type: string
                          description: "Текст комментария"
                        created_at:
                          type: integer
                          description: "Дата и время создания комментария"
                        images:
                          type: array
                          items:
                            type: string
                            description: "url изображения"
                example:
                  comments: [ 
                    { 
                      id: 1, 
                      user_id: 123, 
                      text: "Great route!", 
                      created_at: 1616179200, 
                      images: ["url1", "url2"]
                    } 
                  ]

  /api/comment/review/{review-id}/comment:
    post:
      summary: "Добавление комментария"
      description: "Позволяет пользователю добавить комментарий к рецензии."
      parameters:
        - in: path
          name: review-id
          required: true
          schema:
            type: string
          description: "ID рецензии"
        - in: header
          name: session-token
          required: true
          schema:
            type: string
          description: "Токен сессии"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: integer
                  description: "ID пользователя"
                  example: 1
                text:
                  type: string
                  description: "Текст комментария"
                  example: "This is an amazing route!"
      responses:
        200:
          description: "Комментарий успешно добавлен"

    delete:
      summary: "Удаление комментария"
      description: "Позволяет пользователю удалить комментарий к рецензии."
      parameters:
        - in: path
          name: review-id
          required: true
          schema:
            type: string
          description: "ID рецензии"
        - in: header
          name: session-token
          required: true
          schema:
            type: string
          description: "Токен сессии"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: integer
                  description: "ID пользователя"
                  example: 1
                comment_id:
                  type: integer
                  description: "ID комментария"
                  example: 1
      responses:
        200:
          description: "Комментарий успешно удалён"

  /api/collection/collections:
    get:
      summary: "Получение списка подборок"
      description: "Возвращает список id всех доступных подборок."
      parameters:
        - in: query
          name: pagination-page-number
          required: false
          schema:
            type: integer
            minimum: 1
          description: "Номер страницы для отображения (по умолчанию 1)"
          example: 1
        - in: query
          name: pagination-per-page
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 100
          description: "Количество элементов на странице (по умолчанию 10)"
          example: 10
      responses:
        200:
          description: "Список id подборок"
          headers:
            pagination-current-page:
              description: "Текущая страница пагинации"
              schema:
                type: integer
                example: 1
            pagination-total-elements:
              description: "Общее количество страниц"
              schema:
                type: integer
                example: 5
            pagination-per-page:
              description: "Количество элементов на странице"
              schema:
                type: integer
                example: 3
            pagination-total-pages:
              description: "Количество страниц"
              schema:
                type: integer
                example: 1
          content:
            application/json:
              schema:
                type: object
                properties:
                  collections:
                    type: array
                    items:
                      type: integer
                    description: "ID подборки"
                example:
                  collections: [ 
                    1,
                    2,
                    3
                  ]

  /api/collection/collection/{collection-id}:
    get:
      summary: "Получение информации о подборке"
      description: "Возвращает подробную информацию о выбранной подборке."
      parameters:
        - in: path
          name: collection-id
          required: true
          schema:
            type: integer
          description: "ID подборки"
      responses:
        200:
          description: "Информация о подборке"
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    type: object
                    properties:
                      user_id:
                        type: integer
                        description: "ID пользователя"
                      name:
                        type: string
                        description: "Имя пользователя"
                      image_url:
                        type: string
                        description: "URL аватара пользователя"
                  collection:
                    type: object
                    properties:
                      collection_id:
                        type: int
                        description: "ID подборки"
                      name:
                        type: string
                        description: "Название подборки"
                      url:
                        type: string
                        description: "URL подборки"
                      description:
                        type: string
                        description: "Описание подборки"
                      tags:
                        type: array
                        items:
                          type: string
                          enum: ["forest", "park", "near_water"]
                        description: "Теги подборки"
                      rating:
                        type: number
                        format: float
                        description: "Средний рейтинг подборки"
                      created_at:
                        type: integer
                        description: "Дата создания подборки в формате Unix"
                      routes:
                        type: object
                        properties:
                          amount:
                            type: integer
                            description: "Количество маршрутов в подборке"
                          ids:
                            type: array
                            items:
                              type: integer
                            description: "Список id маршрутов в подборке"
                example:
                  user: 
                    user_id: 1
                    name: "Алла Майонезова"
                    image_url: "image"
                  collection: 
                    collection_id: 1 
                    name: "Best Mountain Trails" 
                    url: "url"
                    description: "adasasdassd"
                    tags: ["forest", "park"]
                    rating: 4.5
                    created_at: 1616179200
                    routes: 
                      amount: 2
                      ids: [1, 2]

  /api/collection/collection:
    post:
      summary: "Создание новой подборки"
      description: "Позволяет пользователю создать новую подборку."
      parameters:
        - in: header
          name: session-token
          required: true
          schema:
            type: string
          description: "Токен сессии"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: integer
                  description: "ID пользователя"
                name:
                  type: string
                  description: "Название подборки"
                description:
                  type: string
                  description: "Описание подборки"
                tags:
                  type: array
                  items:
                    type: string
                    enum: ["forest", "park", "near_water"]
                  description: "Список тегов"
              example:
                user_id: 1
                name: "Favorite Trails"
                description: "Something about route"
                tags: ["forest", "park"]
      responses:
        201:
          description: "Подборка успешно создана"

    put:
      summary: "Обновление подборки"
      description: "Позволяет пользователю обновить существующую подборку. (Добавлять только измененные, то есть если name изменен, то его и добавлять в тело, а остальные - нет)"
      parameters:
        - in: header
          name: session-token
          required: true
          schema:
            type: string
          description: "Токен сессии"
        - in: header
          name: collection-id
          required: true
          schema:
            type: integer
          description: "ID подборки"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: integer
                  description: "ID пользователя"
                name:
                  type: string
                  description: "Название подборки"
                description:
                  type: string
                  description: "Описание подборки"
                tags:
                  type: array
                  items:
                    type: string
                    enum: ["forest", "park", "near_water"]
                  description: "Список тегов"
              example:
                user_id: 1
                description: "A beautiful trail in the mountains" 
      responses:
        200:
          description: "Подборка успешно обновлена"

    delete:
      summary: "Удаление подборки"
      description: "Позволяет пользователю удалить существующую подборку."
      parameters:
        - in: header
          name: session-token
          required: true
          schema:
            type: string
          description: "Токен сессии"
        - in: header
          name: collection-id
          required: true
          schema:
            type: integer
          description: "ID подборки"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: integer
                  description: "ID пользователя"
                  example: 1

      responses:
        200:
          description: "Подборка успешно удалена"

  /api/collection/collection/{collection-id}/add/{route-id}:
    put:
      summary: "Добавление маршрута в подборку"
      description: "Позволяет пользователю добавить маршрут в указанную подборку."
      parameters:
        - in: header
          name: session-token
          required: true
          schema:
            type: string
          description: "Токен сессии"
        - in: path
          name: collection-id
          required: true
          schema:
            type: integer
          description: "ID подборки"
        - in: path
          name: route-id
          required: true
          schema:
            type: integer
          description: "ID маршрута"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: integer
                  description: "ID пользователя"
                  example: 1
      responses:
        200:
          description: "Маршрут успешно добавлен в подборку"

  /api/collection/collection/{collection-id}/remove/{route-id}:
    delete:
      summary: "Удаление маршрута из подборки"
      description: "Позволяет пользователю удалить маршрут из указанной подборки."
      parameters:
        - in: header
          name: session-token
          required: true
          schema:
            type: string
          description: "Токен сессии"
        - in: path
          name: collection-id
          required: true
          schema:
            type: integer
          description: "ID подборки"
        - in: path
          name: route-id
          required: true
          schema:
            type: integer
          description: "ID маршрута"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: integer
                  description: "ID пользователя"
                  example: 1
      responses:
        200:
          description: "Маршрут успешно удален из подборки"
  
  /api/media/image/{image-url}:
    get:
      summary: "Получение изображения"
      description: "Позволяет получить изображение."
      parameters:
        - in: path
          name: image-url
          required: true
          schema:
            type: string
          description: "url изображения"
      responses:
        200:
          description: "Успешно получено изображение"
          content:
            image/jpeg:
              schema:
                type: string
                format: binary
  
  /api/moderation/entity/report:
    post:
      summary: "Жалоба"
      description: "Отправка жалобы на объект, такой как пользователь, комментарий, рецензия, пост или маршрут"
      parameters:
        - in: header
          name: session-token
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: integer
                  description: "ID пользователя"
                object_type:
                  type: string
                  enum: ["user", "review", "route", "comment"]
                object_id:
                  type: integer
                reason:
                  type: string
                  enum: ["spam or advertising", "inappropriate content", "violation of community rules", "offensive content"]
                details:
                  type: string
              example:
                user_id: 1
                object_type: "route"
                object_id: 1
                reason: "inappropriate content"
                details: "This route contains inappropriate language."
      responses:
        200:
          description: "Жалоба успешно отправлена"

  /api/moderation/entity/reports:
    get:
      summary: "Получение списка всех жалоб для модерации"
      description: "Получение всех отправленных жалоб, которые нуждаются в модерации"
      parameters:
        - in: header
          name: session-token
          required: true
          schema:
            type: string
        - in: query
          name: pagination-page-number
          required: false
          schema:
            type: integer
            minimum: 1
          description: "Номер страницы для отображения (по умолчанию 1)"
          example: 1
        - in: query
          name: pagination-per-page
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 100
          description: "Количество элементов на странице (по умолчанию 10)"
          example: 10
        - in: query
          name: status
          required: true
          schema:
            type: string
            enum: ["opened", "closed"]
          description: "Статус репорта"
          example: "opened"
      responses:
        200:
          description: "Список жалоб"
          headers:
            pagination-current-page:
              description: "Текущая страница пагинации"
              schema:
                type: integer
                example: 1
            pagination-total-elements:
              description: "Общее количество страниц"
              schema:
                type: integer
                example: 5
            pagination-per-page:
              description: "Количество элементов на странице"
              schema:
                type: integer
                example: 3
            pagination-total-pages:
              description: "Количество страниц"
              schema:
                type: integer
                example: 1
          content:
            application/json:
              schema:
                type: object
                properties:
                  reports:
                    type: array
                    items:
                      type: object
                      properties:
                        report_id:
                          type: integer
                        user_id:
                          type: integer
                        object_type:
                          type: string
                          enum: ["user", "review", "route", "comment"]
                        object_id:
                          type: integer
                        reason:
                          type: string
                          enum: ["spam or advertising", "inappropriate content", "violation of community rules", "offensive content"]
                        details:
                          type: string
                        created_at:
                          type: integer
                          format: int64
                        closed_at:
                          type: integer
                          format: int64
                        status:
                          type: string
                          enum: ["opened", "closed"]
                example:
                  {
                    "reports": [
                      { 
                        "report_id": 1, 
                        "user_id": 1,
                        "object_type": "route", 
                        "object_id": 1, 
                        "reason": "inappropriate content", 
                        "details": "This route contains inappropriate language.", 
                        "status": "closed", 
                        "created_at": 1616179200,
                        "closed_at": 1616179200
                      }
                    ]
                  }

  /api/moderation/entity/report/resolve:
    post:
      summary: "Закрытие жалобы после рассмотрения"
      description: "Отметка жалобы как решённой после рассмотрения модератором"
      parameters:
        - in: header
          name: session-token
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: integer
                  description: "ID пользователя"
                report_id:
                  type: integer
                resolution:
                  type: string
              example:
                user_id: 1
                report_id: 1
                resolution: "The issue has been resolved, and the content has been edited."
      responses:
        200:
          description: "Жалоба успешно закрыта"

  /api/moderation/bug/report:
    post:
      summary: "Отправка отчёта об ошибке"
      description: "Отправка отчёта о найденной ошибке для её дальнейшего рассмотрения."
      parameters:
        - in: header
          name: session-token
          required: true
          schema:
            type: string
          description: "Токен сессии"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: integer
                description:
                  type: string
              example:
                user_id: 1
                description: "The app crashes when trying to upload a large file."
      responses:
        200:
          description: "Отчёт об ошибке успешно отправлен"

  /api/moderation/bug/reports:
    get:
      summary: "Получение списка баг-репортов"
      description: "Получение всех отправленных отчётов об ошибках для модераторов или разработчиков."
      parameters:
        - in: header
          name: session-token
          required: true
          schema:
            type: string
          description: "Токен сессии"
        - in: query
          name: pagination-page-number
          required: false
          schema:
            type: integer
            minimum: 1
          description: "Номер страницы для отображения (по умолчанию 1)"
          example: 1
        - in: query
          name: pagination-per-page
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 100
          description: "Количество элементов на странице (по умолчанию 10)"
          example: 10
      responses:
        200:
          description: "Список баг-репортов"
          headers:
            pagination-current-page:
              description: "Текущая страница пагинации"
              schema:
                type: integer
                example: 1
            pagination-total-elements:
              description: "Общее количество страниц"
              schema:
                type: integer
                example: 5
            pagination-per-page:
              description: "Количество элементов на странице"
              schema:
                type: integer
                example: 3
            pagination-total-pages:
              description: "Количество страниц"
              schema:
                type: integer
                example: 1
          content:
            application/json:
              schema:
                type: object
                properties:
                  bug_reports:
                    type: array
                    items:
                      type: object
                      properties:
                        report_id:
                          type: integer
                        user_id:
                          type: integer
                        description:
                          type: string
                        status:
                          type: string
                          enum: ["opened", "closed"]
                        created_at:
                          type: integer
                        closed_at:
                          type: integer
                      example:
                        report_id: 1
                        user_id: 1
                        description: "The app crashes when trying to upload a large file."
                        status: "opened"
                        created_at: 1616179200
                        closed_at: 1616179200

  /api/moderation/bug/report/resolve:
    post:
      summary: "Закрытие баг-репорта"
      description: "Отметка баг-репорта как решённого после исправления."
      parameters:
        - in: header
          name: session-token
          required: true
          schema:
            type: string
          description: "Токен сессии"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: integer
                  description: "ID пользователя"
                report_id:
                  type: string
                resolution:
                  type: string
              example:
                user_id: 1
                report_id: 1
                resolution: "Fixed the file upload issue by optimizing memory handling."
      responses:
        200:
          description: "Баг-репорт успешно закрыт"

  /api/moderation/routes:
    get:
      summary: "Получение списка маршрутов, ожидающих модерации"
      description: "Получение маршрутов, которые требуют одобрения перед публикацией."
      parameters:
        - in: header
          name: session-token
          required: true
          schema:
            type: string
        - in: query
          name: pagination-page-number
          required: false
          schema:
            type: integer
            minimum: 1
          description: "Номер страницы для отображения (по умолчанию 1)"
          example: 1
        - in: query
          name: pagination-per-page
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 100
          description: "Количество элементов на странице (по умолчанию 10)"
          example: 10
        - in: query
          name: status
          required: true
          schema:
            type: string
            enum: ["pending", "approved", "rejected"]
          description: "Статус репорта"
          example: "approved"
      responses:
        200:
          description: "Список маршрутов, ожидающих модерации"
          headers:
            pagination-current-page:
              description: "Текущая страница пагинации"
              schema:
                type: integer
                example: 1
            pagination-total-elements:
              description: "Общее количество страниц"
              schema:
                type: integer
                example: 5
            pagination-per-page:
              description: "Количество элементов на странице"
              schema:
                type: integer
                example: 3
            pagination-total-pages:
              description: "Количество страниц"
              schema:
                type: integer
                example: 1
          content:
            application/json:
              schema:
                type: object
                properties:
                  routes:
                    type: array
                    items:
                      type: object
                      properties:
                        user:
                          type: object
                          properties:
                            user_id:
                              type: integer
                              description: "ID юзера"
                              example: 1
                            name:
                              type: string
                              description: "ID юзера"
                              example: "Алла Иванова"
                            image_url:
                              type: string
                              description: "url аватарки"
                              example: "url"
                        route:
                          type: object
                          properties:
                            route_id:
                              type: integer
                              description: "ID маршрута"
                              example: 123
                            name:
                              type: string
                              description: "Название маршрута"
                              example: "Mountain Trail"
                            url:
                              type: string
                              description: "URL маршрута"
                              example: "url"
                            description:
                              type: string
                              description: "Описание маршрута"
                              example: "A beautiful trail in the mountains"
                            length:
                              type: integer
                              description: "Длина маршрута в метрах"
                              example: 5000
                            duration:
                              type: integer
                              description: "Продолжительность маршрута в секундах"
                              example: 7200
                            tags:
                              type: array
                              items:
                                type: string
                                enum: ["forest", "park", "near_water"]
                              description: "Теги маршрута"
                              example: ["forest", "near_water"]
                            category:
                              type: string
                              enum: ["walking"]
                              description: "Категория маршрута"
                              example: "walking"
                            created_at:
                              type: integer
                              description: "Дата создания маршрута в формате Unix"
                              example: 1616179200
                            status:
                              type: string
                              enum: ["pending", "approved", "rejected"]
                              description: "Статус маршрута"
                              example: "approved"
                            is_deleted:
                              type: boolean
                              description: "Флаг удаления маршрута"
                              example: false
                            rating:
                              type: number
                              format: float
                              description: "Средний рейтинг маршрута"
                              example: 3.5
                            images:
                              type: array
                              items:
                                type: string
                              description: "Ссылки на изображения маршрута"
                              example: ["url_to_image1", "url_to_image2"]
                        points:
                          type: array
                          description: "Точки маршрута с координатами и дополнительной информацией"
                          items:
                            type: object
                            properties:
                              point_id:
                                type: integer
                                description: "ID точки маршрута"
                                example: 1
                              coordinate:
                                type: object
                                properties:
                                  latitude:
                                    type: number
                                    format: float
                                    description: "Широта"
                                    example: 45.12345
                                  longitude:
                                    type: number
                                    format: float
                                    description: "Долгота"
                                    example: 12.12345
                              time_offset:
                                type: integer
                                description: "Время в секундах с начала маршрута"
                                example: 300
                              elevation:
                                type: integer
                                description: "Высота точки над уровнем моря в метрах"
                                example: 200
                              speed:
                                type: number
                                format: float
                                description: "Скорость на этой точке маршрута"
                                example: 2.5
                              point_description:
                                type: string
                                description: "Описание точки маршрута"
                                example: "Поворот у дерева"
                              images:
                                type: array
                                items:
                                  type: string
                                description: "Изображения, связанные с точкой маршрута"
                                example: ["url_to_image1", "url_to_image2"]
                      example:
                        user:
                          user_id: 1
                          name: "Алла Майонезова"
                          image_url: "image"
                        route:
                          route_id: 123
                          name: "Mountain Trail"
                          url: "url"
                          description: "A beautiful trail in the mountains"
                          length: 5000
                          duration: 7200
                          tags: ["forest", "near_water"]
                          category: "walking"
                          created_at: 1616179200
                          rating: 3.5
                          images: ["url_to_image1", "url_to_image2"]
                        points:
                          - point_id: 1
                            coordinate:
                              latitude: 45.12345
                              longitude: 12.12345
                            time_offset: 300
                            elevation: 200
                            speed: 2.5
                            point_description: "Поворот у дерева"
                            images: ["url_to_image1", "url_to_image2"]

  /api/moderation/route/approve:
    post:
      summary: "Одобрение маршрута"
      description: "Позволяет модератору одобрить маршрут."
      parameters:
        - in: header
          name: session-token
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: integer
                  description: "ID пользователя"
                object_type:
                  type: string
                  enum: ["route", "post", "comment", "collection"]
                object_id:
                  type: integer
              example:
                user_id: 1
                object_type: "route"
                object_id: 1
      responses:
        200:
          description: "Маршрут успешно одобрен"

  /api/moderation/route/reject:
    post:
      summary: "Отклонение маршрута"
      description: "Позволяет модератору отклонить маршрут."
      parameters:
        - in: header
          name: session-token
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: integer
                  description: "ID пользователя"
                object_type:
                  type: string
                  enum: ["route", "post", "comment", "collection"]
                object_id:
                  type: integer
                reason:
                  type: string
              example:
                user_id: 1
                object_type: "route"
                object_id: 1
                reason: "The route description is incomplete."
      responses:
        200:
          description: "Маршрут отклонён"
                                                             
  /api/auth/register:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
      responses:
        '201':
          description: User registered successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegisterResponse'
        '409':
          description: User may already exist
        '500':
          description: Internal server error

  /api/auth/login:
    post:
      summary: Log in a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: User logged in successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
        '401':
          description: Unauthorized
        '500':
          description: Internal server error

  /api/auth/check_token:
    get:
      summary: Check if the token is valid
      parameters:
        - name: session-token
          in: header
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Token is valid
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  user_id:
                    type: string
        '400':
          description: Invalid session-token
        '401':
          description: Unauthorized
        '500':
          description: Internal server error

  /api/auth/vk:
    post:
      summary: Log in a user via VK
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VkAuthParams'
      responses:
        '200':
          description: User logged in via VK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
        '401':
          description: Unauthorized
        '500':
          description: Internal server error

components:
  schemas:
    RegisterRequest:
      type: object
      properties:
        username:
          type: string
        email:
          type: string
          format: email
        password:
          type: string
        name:
          type: string

    RegisterResponse:
      type: object
      properties:
        user_id:
          type: integer
        token:
          type: string

    LoginRequest:
      type: object
      properties:
        email:
          type: string
          format: email
        password:
          type: string

    LoginResponse:
      type: object
      properties:
        token:
          type: string
        refresh_token:
          type: string

    VkAuthParams:
      type: object
      properties:
        code:
          type: string

    VkTokenResponse:
      type: object
      properties:
        access_token:
          type: string
        expires_in:
          type: integer
        user_id:
          type: integer
        email:
          type: string
          nullable: true